### ISSUE TITLE
CLASSIC Wholly tooltips

### ISSUE THREAD

**Issue by Nerillida** [smaitch/Wholly#20]
Regarding Wholly's tooltip display of quests in its list, as mentioned in Grail ticket #67, the display does not seem to respect any action except those on the quest entry, i.e. not the one derived from the quest giver etc.

![Screen Shot 2019-10-02 at 19 19 15](https://user-images.githubusercontent.com/55858788/66070969-31f52200-e54a-11e9-873c-7133e728d898.png)

**Comment by smaitch** [comment]
I do not understand what you are reporting.

When we associate a faction with a quest giver this allows Grail to know whether a player of a specific faction can get the quest without the quest needing to be marked specifically for that faction.

This should allow the quests in Wholly's quest panel to have the proper status (appearing brown by default), and also not to appear on the map since unobtainable quests never appear on the map.

Also, in the tooltip above the name of the quest giver would appear in red if the NPC is hostile to the player, otherwise it appears as above.

**Comment by Nerillida** [comment]
It's the Faction Both part.
It's not accurate. May be something that you want to deal with, or not.

**Comment by smaitch** [comment]
I understand.  That both is coming from the quest specifically.  It turns out that Blizzard has not marked that quest to be associated with a faction specifically, but the quest giver has a faction.  Wholly has indicated the quest association with that "Both", and I kept it that way when adding the factions to the NPCs.  I can understand how it can be confusing seeing "Both" when you know it is definitely not.  I will think about how to convey that the quest is not marked with a faction by Blizzard (normally resulting in "Both"), but can only be gotten by a faction based on NPC.

**Comment by Nerillida** [comment]
I did not know that the quests returned factions. In my research, I have got the factions for all the quest that I have researched. Some get their faction by the NPC that s the turn-in aspect i.e. from a neutral to an Alliance. You have some FA/FH in your quest data, do you have any objection to the faction being added to more?
Thanks.

**Comment by smaitch** [comment]
Actually, I am automating how the faction associated with the quest is assigned.  I used to just associate the faction with the quest manually, but then the automatic system was overwriting things.  That is why the fA and fH were created to make my automated system not overwrite.  However, I think the proper solution is to keep my automated system in place, and just update the quest givers with proper faction information.  Therefore, it is best not to assign factions to the quests but rather to the quests' NPCs.

**Comment by Nerillida** [comment]
And use the quest FA/FH for when your system will not work, I.e. neutral giver to alliance turn-in. 
I noticed that som inanimate objects/items had acquired factions.

**Comment by smaitch** [comment]
There is a quest in Hillsdrad that should only be done by Alliance, but the quest itself appears neutral so I tried to compensate with an FA on the object.  This may not work, so I might need to put fA on the quest.

**Comment by Nerillida** [comment]
> Therefore, it is best not to assign factions to the quests but rather to the quests' NPCs
That's 600+ quests to go through to work out which is which.
Ho hum…

**Comment by smaitch** [comment]
Actually just ignore the quests.  When we add new NPCs we just need to ensure their faction is set.  If you are talking about Retail it is a much larger problem as there are tons more NPCs in the database there.

**Comment by smaitch** [comment]
The next version of Grail has been updated to mark the quest faction based on both how the quest is marked and by how the NPC factions are marked.
