### ISSUE TITLE
Wholly Classic v Retail

### ISSUE THREAD

**Issue by Nerillida** [smaitch/Wholly#27]
I downloaded the latest pair of Wholly/Grail. The file labelled as the Classic version does not do what you state it doe i.e. used more standard colours for the quests in progress. It colours completed as green. and no pin for uncompleted.

I am not sure what "Updates the Classic Wholly quest panel to have a right side." as it always has done so for me, unless we are taking at cross purposes.
I used the non-Classicfile, it works fine from map pin point of view.

**Comment by smaitch** [comment]
Since you were using the older version that has the color as green for complete, you should use the preferences and reset the colors.  This should make turnin be yellow, not complete be white and failed be red.
If you have a screen shot from the previous version to the current one you can see a slight difference.  The main thing is the old version had overlapping textures that could make things not look right if they were applied in the wrong order.  The new version should not have that happen.

**Comment by Nerillida** [comment]
I have found the problem. Or maybe, if I use show quests with prerequisites, the same NPCs quest turn-in pins are hidden by the red exclamation points.
A suggestion might be to draw the turn-in pins at a higher level?

But the green completed pins are still there.
cccc
cccc
cccc
Wholly preferences
![Wholly preferences Main](https://user-images.githubusercontent.com/55858788/68424318-a0f21600-019b-11ea-9759-7ddc102b1851.png)
![Wholly preferences 1](https://user-images.githubusercontent.com/55858788/68424319-a18aac80-019b-11ea-998e-886a31febf4f.png)
![Wholly preferences 2](https://user-images.githubusercontent.com/55858788/68424320-a18aac80-019b-11ea-92bd-b784798c5024.png)
![Wholly preferences 3](https://user-images.githubusercontent.com/55858788/68424321-a18aac80-019b-11ea-9d70-7105c1a7c411.png)
![Wholly preferences 4](https://user-images.githubusercontent.com/55858788/68424323-a18aac80-019b-11ea-9e7e-bd0e4dc8522d.png)
![Wholly preferences 5](https://user-images.githubusercontent.com/55858788/68424324-a18aac80-019b-11ea-8ce4-bd2fd165b7d7.png)

Quest turn-in obscured
![Quest turn-in obscured](https://user-images.githubusercontent.com/55858788/68424082-29bc8200-019b-11ea-9984-7b35c2526ecf.png)

Quest incomplete
![Quest incomplete](https://user-images.githubusercontent.com/55858788/68424010-0691d280-019b-11ea-8190-37229b2ddc91.png)

Quests completed
![Quests completed](https://user-images.githubusercontent.com/55858788/68423934-e5c97d00-019a-11ea-9875-9926c1dcd61e.png)

Could it be that yourchangesdidnot "take" on the released version.

![tocfile](https://user-images.githubusercontent.com/55858788/68424464-f4fcfa80-019b-11ea-8c93-003af7c1fc4f.png)

**Comment by smaitch** [comment]
I believe the code is correct.  The priority is set so a completed quest ready for turn-in has highest priority.  The quests that are not complete and failed have the lowest priority.  This means if the quest giver that accepts a turn-in has a quest that needs prerequisites, it will appear as a red exclamation point until the quest is ready for turn-in.  At that point it will appear as a yellow question mark.  The reason this order was chosen was because (1) the most important information should be shown first, and to me that was the completed quest and then other quest information as it has been, (2) the tooltip has the rest of the turn-in quests in it so you can see that the quest giver actually is one you use for turn-in as well (because of the purple quests in the tooltip).  The fact that you have a quest that eventually can be turned in was not that important in my thoughts versus there are more quests to get from someone.

To reset the colors did you press this button on the bottom of the main preferences for Wholly?

<img width="332" alt="Screen Shot 2019-11-07 at 17 16 38" src="https://user-images.githubusercontent.com/18412543/68432699-f7068f80-0182-11ea-8904-6db9062f6fd5.png">

**Comment by Nerillida** [comment]
> To reset the colors did you press this button on the bottom of the main preferences for Wholly?

https://i.imgur.com/iWKad22.jpg
