### ISSUE TITLE
Unobtainable vs Completed

### ISSUE THREAD

**Issue by puggan** [smaitch/Wholly#5]
If a quest is both Unobtainable vs Completed.

Shouldn't it be primarly counted as Completed?

Right now it's acts as Unobtainable.

![screen shot 2017-09-30 at 11 25 24](https://user-images.githubusercontent.com/866668/31044612-d97dd710-a5d2-11e7-82e0-59dcd62c0a28.png)

(Also part of https://github.com/puggan/Grail/issues/14)

**Comment by smaitch** [comment]
The problem we run in to is Blizzard sometimes marks complete other quests that you do not actually do.  This happens a lot with a quest from the other faction that is the same as the one you complete.  So, Grail will see it as completed, but you should also not be able to get it because it belongs to the other faction.  This can also happen with quests that are based on a selection like the arena versus lumber mill.  You may complete all the quests down one line and then change the building to do the other quests.  The first set are no longer obtainable even though they have been completed.  It happens with quests that are only available at specific levels and specific faction levels as well.  We side on the side of "this is what is available/unavailable NOW, no matter what happened before".

**Comment by puggan** [comment]
Thanks for the explenation, looked wrong for an outsider, but if thats how wow act, then it's understandable.
